{% set name = "addfips" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/addfips-{{ version }}.tar.gz
  sha256: 71008c3937add36670d2a7d301213dbee301941662c5ebe673639677eedb7053

build:
  number: 1
  noarch: python
  entry_points:
    - addfips=addfips.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - importlib_resources >=5.0
    - python >=3.7.5

test:
  imports:
    - addfips
  commands:
    - pip check
    - addfips --help
  requires:
    - pip

about:
  home: https://github.com/fitnr/addfips/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: AddFIPS is a tool for adding state or county FIPS codes to files that contain just the names of those geographies.

  description: |
    AddFIPS is a tool for adding state or county FIPS codes to files that
    contain just the names of those geographies. FIPS codes are the official
    ID numbers of places in the US. They're invaluable for matching data from
    different sources.
  doc_url: https://github.com/fitnr/addfips/
  dev_url: https://github.com/fitnr/addfips/

extra:
  recipe-maintainers:
    - zaneselvans
    - zschira
